version: 2.1

container_config: &container_config
  docker:
    - image: mloweedgar/node-aws-cli

commands:
  setup_project_files:
    description: Checkout and install node packages
    steps:
      - checkout
      - run:
          name: Install angular cli
          command: npm install -g @angular/cli
      - run:
          name: Install node packages
          command: npm install

jobs:
  deploy_to_production:
    <<: *container_config
    steps:
      - setup_project_files
      - run:
          name: Build for production
          command: ng build --prod
      - run:
          name: Deploy to S3
          command: aws s3 sync dist s3://sndbx-landingpage --delete
workflows:
  version: 2.1
  build:
    jobs:
      - deploy_to_production:
          filters:
            branches:
              only: main